/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loginform;

/**
 *
 * @author trant
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        setLocationRelativeTo(null);
        txt_username.setBackground(new java.awt.Color(0,0,0,1));
        txt_password.setBackground(new java.awt.Color(0,0,0,1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        lbl_login = new javax.swing.JLabel();
        lbl_hello = new javax.swing.JLabel();
        lbl_username = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        lbl_input1 = new javax.swing.JLabel();
        icon_user = new javax.swing.JLabel();
        lbl_forget = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        lbl_input2 = new javax.swing.JLabel();
        icon_disable = new javax.swing.JLabel();
        icon_show = new javax.swing.JLabel();
        chk_remember = new javax.swing.JCheckBox();
        lbl_password = new javax.swing.JLabel();
        btn_login = new javax.swing.JButton();
        lbl_account = new javax.swing.JLabel();
        lbl_signup = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Authentication.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 484));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 490));

        jPanel2.setBackground(new java.awt.Color(25, 118, 212));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("x");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        jPanel2.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 30, 30));

        lbl_login.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lbl_login.setForeground(new java.awt.Color(255, 255, 255));
        lbl_login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_login.setText("Login");
        jPanel2.add(lbl_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 51, 438, -1));

        lbl_hello.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbl_hello.setForeground(new java.awt.Color(255, 255, 255));
        lbl_hello.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_hello.setText("Hello! Let's get started");
        jPanel2.add(lbl_hello, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 105, 438, 34));

        lbl_username.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbl_username.setForeground(new java.awt.Color(199, 226, 255));
        lbl_username.setText("Username");
        jPanel2.add(lbl_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 145, 372, -1));

        txt_username.setFont(txt_username.getFont().deriveFont(txt_username.getFont().getSize()+2f));
        txt_username.setForeground(new java.awt.Color(255, 255, 255));
        txt_username.setBorder(null);
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        jPanel2.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 162, 310, 30));

        lbl_input1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_input1.setText("_________________________________________________________________");
        jPanel2.add(lbl_input1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 169, 320, 32));

        icon_user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_user_20px_1.png"))); // NOI18N
        jPanel2.add(icon_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 169, 37, -1));

        lbl_forget.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbl_forget.setForeground(new java.awt.Color(199, 226, 255));
        lbl_forget.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_forget.setText("Forget password?");
        lbl_forget.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(lbl_forget, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 304, 132, -1));

        txt_password.setFont(txt_password.getFont().deriveFont(txt_password.getFont().getSize()+2f));
        txt_password.setForeground(new java.awt.Color(255, 255, 255));
        txt_password.setBorder(null);
        txt_password.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });
        jPanel2.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 310, 30));

        lbl_input2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_input2.setText("_________________________________________________________________");
        jPanel2.add(lbl_input2, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 240, 320, 32));

        icon_disable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_disable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_invisible_20px_1.png"))); // NOI18N
        icon_disable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icon_disable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_disableMouseClicked(evt);
            }
        });
        jPanel2.add(icon_disable, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 37, -1));

        icon_show.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_eye_20px_1.png"))); // NOI18N
        icon_show.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icon_show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_showMouseClicked(evt);
            }
        });
        jPanel2.add(icon_show, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 37, -1));

        chk_remember.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        chk_remember.setForeground(new java.awt.Color(199, 226, 255));
        chk_remember.setText("Remember password");
        jPanel2.add(chk_remember, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 302, 198, -1));

        lbl_password.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbl_password.setForeground(new java.awt.Color(199, 226, 255));
        lbl_password.setText("Password");
        jPanel2.add(lbl_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 372, -1));

        btn_login.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_login.setForeground(new java.awt.Color(25, 118, 212));
        btn_login.setText("LOGIN");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        jPanel2.add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 351, 368, 40));

        lbl_account.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbl_account.setForeground(new java.awt.Color(199, 226, 255));
        lbl_account.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_account.setText("Don't have an account?");
        jPanel2.add(lbl_account, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 417, 219, -1));

        lbl_signup.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbl_signup.setForeground(new java.awt.Color(255, 255, 255));
        lbl_signup.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_signup.setText("Sign up");
        lbl_signup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(lbl_signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 417, 143, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 450, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_loginActionPerformed

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passwordActionPerformed

    private void icon_disableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_disableMouseClicked
        txt_password.setEchoChar((char)0);
        icon_disable.setVisible(false);
        icon_disable.setEnabled(false);
        icon_show.setEnabled(true);
        icon_show.setEnabled(true);
    }//GEN-LAST:event_icon_disableMouseClicked

    private void icon_showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_showMouseClicked
        txt_password.setEchoChar((char)8226);
        icon_disable.setVisible(true);
        icon_disable.setEnabled(true);
        icon_show.setEnabled(false);
        icon_show.setEnabled(false);
    }//GEN-LAST:event_icon_showMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for (double i = 0.0; i < 1.0; i = i+0.1){
            String val = i + "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try{
                Thread.sleep(50);
            } catch(Exception e){
                
            }
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JCheckBox chk_remember;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel icon_disable;
    private javax.swing.JLabel icon_show;
    private javax.swing.JLabel icon_user;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_account;
    private javax.swing.JLabel lbl_forget;
    private javax.swing.JLabel lbl_hello;
    private javax.swing.JLabel lbl_input1;
    private javax.swing.JLabel lbl_input2;
    private javax.swing.JLabel lbl_login;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_signup;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
